sudo: false
language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - 7.2

env:
    - PHPCS_VERSION='~2.0'
    - PHPCS_VERSION='~2.0@dev'

matrix:
    exclude:
        - php: 5.5
          env: PHPCS_VERSION='~2.0@dev'
        - php: 5.6
          env: PHPCS_VERSION='~2.0@dev'
        - php: 7.0
          env: PHPCS_VERSION='~2.0@dev'
        - php: 7.1
          env: PHPCS_VERSION='~2.0@dev'

before_script:
    - composer require satooshi/php-coveralls:^1.0 squizlabs/php_codesniffer:$PHPCS_VERSION --prefer-source

script:
    - mkdir -p build/logs
    - phpunit --coverage-clover build/logs/clover.xml

after_script:
    - php vendor/bin/coveralls -v
    - wget https://scrutinizer-ci.com/ocular.phar -t 3
    - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
