<?php

trait TSomeEventHandlerFeature
{

    /**
     * [HOOK] Not the event.
     *
     * @return void
     */
    protected function someMethod()
    {

    }

    /**
     * [HOOK] Not the event.
     *
     * @return void
     */
    protected function OnSomething()
    {

    }

    /**
     * hOOK] Not the event.
     *
     * @return void
     */
    protected function OnSomethingOther()
    {

    }
}

?>
