<?php
//'do {EOL...} while (...);EOL',
do {
} while ($condition);
do{
} while ($condition);
do
{
} while ($condition);
do {
}while ($condition);
do {
} while($condition);
do {
}
while ($condition);
do {
} while ($condition)
;
//'while (...) {EOL',
while ($condition) {
}
while($condition) {
}
while ($condition){
}
while ($condition)
{
}
//'switch (...) {EOL',
switch ($condition) {
}
switch($condition) {
}
switch ($condition){
}
switch ($condition)
{
}
//'for (...) {EOL',
for ($i = 0; $i < 5; $i++) {
}
for($i = 0; $i < 5; $i++) {
}
for ($i = 0; $i < 5; $i++){
}
for ($i = 0; $i < 5; $i++)
{
}
//'if (...) {EOL',
if ($condition) {
}
if($condition) {
}
if ($condition){
}
if ($condition)
{
}
//'foreach (...) {EOL',
foreach ($condition) {
}
foreach($condition) {
}
foreach ($condition){
}
foreach ($condition)
{
}
//'}EOLelseif (...) {EOL',
if ($condition) {
}
elseif ($condition) {
}
if ($condition) {
} elseif ($condition) {
}
if ($condition) {
}
elseif($condition) {
}
if ($condition) {
}
elseif ($condition){
}
if ($condition) {
}
elseif ($condition)
{
}
//'}EOLelse {EOL',
if ($condition) {
}
else {
}
if ($condition) {
} else {
}
if ($condition) {
}
else{
}
if ($condition) {
}
else
{
}
//'do {EOL',
do {
} while ($condition);
do{
} while ($condition);
do
{
} while ($condition);
?>
